### ISSUE TITLE
Firefox 39

### ISSUE THREAD

**Issue by juneyourtech** [sumzary/yt2p#1]
For various reasons, I've stayed with Firefox 39. For several years, this has been the combination that's permitted me to have stable Flash playback on YouTube. I've kept that going, because Firefox 40 no longer allowed Flash to be stable enough. wrt other functionality, Firefox 43.0 is the last one to support cookie prompting.

I haven't buried the idea of Flash yet, but am considering YT2P.

The issue is, that context menu items do not work in version 2.0.1. When adding the path to vlc.exe in the command, then I get this error: "Command pattern is not setup correctly for this player."

YT2P 1.5 invokes VLC, but the link(s) sent to VLC do not appear to work any longer. If possible, I'll stay with Firefox 39.0 in the hopes of somhow keeping stutter-less Flash-based playback. And I'll never upgrade to anything newer beyond Firefox 43.0. Because cookie prompts.

Therefore, would it be possible to have support for older Firefox, at least going back to 38.8esr? I recently learned about some users who use even older ESR versions of Firefox, but that sounds like a stretch.

**Comment by Infobott** [comment]
The so called 'fancy links' are always bloodred! Isn't it possible to make it a different color? It would be nice if the color could be chosen. In fact I would like no color at all.

**Comment by juneyourtech** [comment]
I recently got an update to YT2P version 2.1 on Firefox 39.0, so the particular issue of availability to (slightly older) browsers is resolved. Thanks.

**Comment by juneyourtech** [comment]
@Infobott Your issue is unrelated to the one _I_ started, so you could start a new issue related to link colour.
